### ISSUE TITLE
add `owners` resource with `get` and `list` subcommands

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq-cli#36]
Command would call the `v3/owners` api resource. You could `list` all manufacturers or `get` one with the `owners_id`. Optional flags could include `--json`, `--pretty`, `--csv`

**Comment by russbiggs** [comment]
related to #42

**Comment by russbiggs** [comment]
@majesticio owners  is now implemented in the openaq-go, upgrade to the latest version to implement this feature

**Comment by majesticio** [comment]
Great, I will start work on adding the `owners` resource to openaq-cli

**Comment by russbiggs** [comment]
resolved in v0.4.0
