### ISSUE TITLE
add optional `providers` flag to `countries list` command

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq-cli#40]
pass a providers ID to `--providers` to fetch a list of countries with that providers ID available.
eg: `openaq countries list --providers 119` to fetch a list of countries with airnow data

**Comment by russbiggs** [comment]
Is this currently implemented in the API? I' get a 500 when trying to pass a `parameters_id=` in the query string

**Comment by majesticio** [comment]
looks like right now we are just counting the providers for the countries resource eg: `"providersCount": 4`

**Comment by russbiggs** [comment]
no longer adding these query params
