### ISSUE TITLE
add optional flags to `providers list` command

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq-cli#41]
## optional flags:
- `--parameters`
-  `--iso`
-  `--monitor`
-  `--countries`
- `--bbox`
- `--coordinates`
- `--radius` *required with coordinates

**Comment by russbiggs** [comment]
are all of these currently implemented in the API?

**Comment by majesticio** [comment]
No, I thought `?parameters_id` was implemented but returns a `500`. So these params are not available yet
