### ISSUE TITLE
Homebrew git dependency

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-cli#65]
I have a feeling that Homebrew taps are similar to Scoop in that it may require git as a dependency to communicate with the repo. It would be worth checking this with a clean OS that does not already have git installed to validate this. 

If git is a required dependency we can add it as a dependency in a similar way to Scoop via the gorelease.yml

```yml
    dependencies:
      - name: git
```

**Comment by majesticio** [comment]
I tested it on a fresh MacOS install and it seemed to work without this, so the dependency management might be better out of box for Homebrew. So its up for debate whether we should add it.

**Comment by russbiggs** [comment]
Interesting and just to confirm macOS did not have git installed prior to the brew tap command

**Comment by majesticio** [comment]
Thats correct, never even opened a terminal window on that machine. Had never user used or installed git

**Comment by russbiggs** [comment]
Great!
