### ISSUE TITLE
Add --mini flag option to countries

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq-cli#7]
desired command: `openaq countries list --mini`

**Comment by russbiggs** [comment]
What would the "mini" output look like as compared to the full output?

**Comment by majesticio** [comment]
I wouldn't it for `countries get` as well like command `openaq countries get 13 --mini` but that is up for debate

**Comment by russbiggs** [comment]
right. the current columns are:

```
 COUNTRIES_ID | ISO_CODE | NAME   | DATETIME_FIRST       | DATETIME_LAST        | PARAMETERS | LOCATIONS_COUNT | MEASUREMENTS_COUNT | PROVIDERS_COUNT
```

what are the columns you are proposing to be included in the --mini version?

**Comment by majesticio** [comment]
ah, perhaps `COUNTRIES_ID` `ISO_CODE` `NAME` & `PARAMETERS`
